FROM node:20-alpine
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
ARG NEXT_PUBLIC_GOOGLE_MAPS_KEY
ARG NEXT_PUBLIC_SOLANA_APP_PUBKEY
ENV NEXT_PUBLIC_GOOGLE_MAPS_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_KEY
ENV NEXT_PUBLIC_SOLANA_APP_PUBKEY=$NEXT_PUBLIC_SOLANA_APP_PUBKEY
RUN npm run build
EXPOSE 8080
ENV PORT=8080
CMD ["npm", "start"]
